### ISSUE TITLE
[Suggestion] Output format option for fairGTrackJsonValidate.py

### ISSUE THREAD

**Issue by dtitov** [fairtracks/fairtracks_validator#12]
Currently, `fairGTrackJsonValidate.py` produces output as plaintext. It would be useful if we could specify the format of the output: either `plaintext` or `json` (so that we get output in the same format as from the web-service).

**Comment by jmfernandez** [comment]
I have just added in f4146d7995192485f5aa5b5c719d5c2cf7ef0d1e several flags to allow storing the internal JSON formatted report in a file (`--report`,`--report-verbose`), as well as being able to silence human readable output (`-q`).
